from app.agent.state import AgentState, AgentStatus
from app.config.logger import app_logger
from app.tools.registry import ToolRegistry


class Executor:
    """
    Executes the plan generated by the Planner.
    """

    def __init__(self):
        self.registry = ToolRegistry()

    def execute(self, state: AgentState) -> AgentState:

        """ Execute every step generated by the planner. Args: state: Current execution state. Returns: Updated AgentState. """

        app_logger.info("Executor started.")

        state.status = AgentStatus.EXECUTING

        for step in state.plan:

            app_logger.info(f"Executing action: {step.action}") 
            
            # Find the appropriate tool 
            tool = self.registry.get_tool(step.action)

            if tool is None:
                app_logger.warning(f"No tool registered for action: {step.action}")
                continue

            app_logger.info(f"Executing action: {step.action}")

            # Execute the tool with parameters generated by the planner 
            result = tool.execute(step.parameters)

            # Store execution result
            state.tool_results[f"{step.action}_{len(state.completed_steps) + 1}"] = result

            # Track completed steps
            state.completed_steps.append(step)

        state.status = AgentStatus.COMPLETED
        state.final_response = "Execution completed successfully."

        return state