# Stores everything happening during one agent execution.

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field
from app.ai.planner_models import PlanStep


class AgentStatus(str, Enum):
    # Represents the current lifecycle stage of an agent execution.

    PENDING = "PENDING"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AgentState(BaseModel):
    """
    Maintains the complete state of a single agent execution.

    Every execution of the agent gets its own AgentState object.
    It acts as the working memory for the current request.
    """

    # User's original instruction
    query: str

    # Current lifecycle status
    status: AgentStatus = AgentStatus.PENDING

    # List of planned actions
    # plan: list[str] = Field(default_factory=list)
    plan: list[PlanStep] = Field(
        default_factory=list,
        description="Execution plan generated by the planner."
    )

    # Actions that have already been executed
    completed_steps: list[str] = Field(default_factory=list)

    # Results returned by tools
    tool_results: dict[str, Any] = Field(default_factory=dict)

    # Any error encountered during execution
    error: str | None = None

    # Final response returned to the API
    final_response: str | None = None