from typing import Any

from pydantic import BaseModel, Field


class PlanStep(BaseModel):
    """
    Represents one executable step generated by the LLM.
    """

    action: str = Field(
        description="Action name understood by the executor."
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters required to execute the action."
    )


class PlannerResponse(BaseModel):
    """
    Complete execution plan returned by the LLM.
    """

    steps: list[PlanStep] = Field(
        default_factory=list,
        description="Ordered list of execution steps."
    )